### ISSUE TITLE
Checklist of Features

### ISSUE THREAD

**Issue by charliettaylor** [Peekoe/gpt-showdown#1]
## Backend
- [x] Database
- [x] CRUD for Questions and Choices
- [ ] endpoints for GPT
- [ ] TCP connections of players

## Frontend
- [ ] Join game page
- [ ] Lobby page
- [ ] Game page
